import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { spawn, spawnSync } from 'node:child_process';
import fs from 'node:fs';
const P = 8899, B = `http://localhost:${P}`, DB = './data/test.db';
const env = { ...process.env, DB_DRIVER: 'node', PORT: P, DATABASE_URL: DB, CORS_ORIGINS: 'http://a.test', PUBLIC_SITE_URL: 'http://a.test', API_URL: B, ADMIN_SESSION_SECRET: 'x'.repeat(40), ALLOWED_DOWNLOAD_HOSTS: 'github.com', ADMIN_BOOTSTRAP_EMAIL: 't@x.io', ADMIN_BOOTSTRAP_PASSWORD: 'correct-horse-battery', LOGIN_RATE_LIMIT_PER_MIN: '50' };
let srv, cookie, csrf;
const H = { 'content-type': 'application/json', origin: 'http://a.test' };
const api = (m, p, b, h = {}) => fetch(B + p, { method: m, redirect: 'manual', headers: { ...H, ...(cookie ? { cookie } : {}), ...(csrf ? { 'x-csrf-token': csrf } : {}), ...h }, body: b ? JSON.stringify(b) : undefined });
before(async () => { fs.rmSync(DB, { force: true }); fs.rmSync(DB + '-wal', { force: true }); fs.rmSync(DB + '-shm', { force: true }); spawnSync('node', ['--disable-warning=ExperimentalWarning', 'src/server.mjs', '--create-admin'], { env }); srv = spawn('node', ['--disable-warning=ExperimentalWarning', 'src/server.mjs'], { env, stdio: 'ignore' }); await new Promise(r => setTimeout(r, 1200)); });
after(() => srv.kill());
test('health + public', async () => { assert.equal((await api('GET', '/health')).status, 200); const r = await (await api('GET', '/api/products')).json(); assert.ok(r.length >= 7); assert.equal((await api('GET', '/api/products/nope')).status, 404); });
test('admin blocked without session', async () => { for (const p of ['/api/admin/products', '/api/admin/stats', '/api/admin/audit']) assert.equal((await api('GET', p)).status, 401); });
test('bad login', async () => assert.equal((await api('POST', '/api/admin/login', { email: 't@x.io', password: 'wrong' })).status, 401));
test('login, csrf, crud, download flow', async () => {
  const l = await api('POST', '/api/admin/login', { email: 't@x.io', password: 'correct-horse-battery' }); assert.equal(l.status, 200);
  cookie = l.headers.get('set-cookie').split(';')[0]; csrf = (await l.json()).csrf;
  assert.ok(l.headers.get('set-cookie').includes('HttpOnly'));
  assert.equal((await api('POST', '/api/admin/products', { slug: 'x', name: 'X' }, { 'x-csrf-token': 'bad' })).status, 403);
  const app = await (await api('POST', '/api/admin/applications', { product_id: 2, platform: 'android' })).json();
  assert.equal((await api('POST', '/api/admin/app_releases', { application_id: app.id, version: '1', url: 'javascript:alert(1)' })).status, 400);
  assert.equal((await api('POST', '/api/admin/app_releases', { application_id: app.id, version: '1', url: 'https://evil.example/a.apk' })).status, 400);
  assert.equal((await api('POST', '/api/admin/app_releases', { application_id: app.id, version: '0.1.0', url: 'https://github.com/o/r/releases/a.apk' })).status, 201);
  const d = await api('GET', '/download/nexchat/android', null, { referer: 'http://a.test/x' }); assert.equal(d.status, 302); assert.match(d.headers.get('location'), /github\.com/);
  await api('GET', '/download/nexchat/android');
  const s = await (await api('GET', '/api/admin/stats')).json(); assert.equal(s.attempts_total, 2); assert.equal(s.unique_total, 1);
  assert.equal((await api('GET', '/download/nexchat/ios')).status, 404);
  assert.equal((await api('POST', '/api/admin/products', { slug: "a'; DROP TABLE products;--", name: 'x' })).status, 400);
  const j = await api('POST', '/api/admin/journal_posts', { slug: 'xss', title: '<script>alert(1)</script>', content: 'x', published: 1 }); assert.equal(j.status, 201);
  assert.equal((await api('POST', '/api/admin/logout')).status, 200);
});
